/* -----------------------------------------------
/* This file is generated by K_BundleTools.cs
/* Author: Kaki
/* Date:2023/4/22 22:37:55
/* ----------------------------------------------- */
namespace Kaki_AssetBundleBuilder
{
	public enum K_BundleModuleEnum
	{
		None,
		a,
		b,
		c,
	}
}
